version: 0.2

phases:
    install: 
        runtime-versions:
            java: corretto8
            docker: 18
    pre_build:
        commands:
            - echo "Pre_build"
            - echo Logging in to Amazon ECR
            - $(aws ecr get-login  --no-include-email --region us-west-2)
    build:
        commands:
            - echo "Build"
            - echo "I am a new Build"
            - echo "Entered build phase"
            - echo "Building Java"
            - cd PolicyMicroservice
            - mvn clean package
            - docker build -t policymicroservice .
            - docker tag policymicroservice 130475542568.dkr.ecr.us-west-2.amazonaws.com/pod-6-policy-registry:policyservice
    post_build:
        commands:
            - echo "Post_build"
            - docker push 130475542568.dkr.ecr.us-west-2.amazonaws.com/pod-6-policy-registry:policyservice
            - printf '[{"name":"policy-container","imageUri":"%s"}]' 130475542568.dkr.ecr.us-west-2.amazonaws.com/pod-6-policy-registry:policyservice > taskdefinition.json
            - cat taskdefinition.json


artifacts:
     files: 
            - PolicyMicroservice/taskdefinition.json

